name: W3C CSS Validation

on:
  pull_request:

jobs:
  validate-css:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install curl
        run: sudo apt-get install -y curl

      - name: Validate CSS
        run: |
          for file in $(find . -name "*.css"); do
             curl -s -F "text=@$file" https://jigsaw.w3.org/css-validator/validator -F "output=json" | jq '.cssvalidation.warnings + .cssvalidation.errors' || exit 1
           done
