name: CSS Validation

on:
  pull_request:

jobs:
  lint-css:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install curl
        run: sudo apt-get install curl

      - name: Get all CSS files
        run: |
          css_files=$(find . -name "*.css" -exec cat {} \;)
          echo "$css_files" > all-css-files.css

      - name: Run CSSLint API
        run: |
          curl -X POST -d "css=$(cat all-css-files.css)" https://csslint.net/api/ | tee lint-result.json

      - name: Check for lint errors
        run: |
          if grep -q "errors" lint-result.json; then
            echo "CSS has some errors!"
            exit 1
          else
            echo "CSS has no erros."
          fi
