name: W3C HTML Validation

on:
  pull_request:

jobs:
  validate-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install curl
        run: sudo apt-get install -y curl

      - name: Validate HTML
        run: |
          for file in $(find . -name "*.html"); do
            curl -H "Content-Type: text/html; charset=utf-8" \
                 --data-binary "@$file" \
                 https://validator.w3.org/nu/ \
                 | jq '.messages[] | select(.type == "error")' || exit 1
          done
